export enum ItenariesRoutesEnum {
  DASHBOARD = '/dashboard',
  ITINERARY = '/itineraries',
  ITINERARY_EXPLORE = '/itineraries/explore',
  ITINERARY_FAVOURITES = '/itineraries/favorites',
  ITINERARY_BUILDER = '/itineraries/builder',
  SEARCH = '/search/',
  REQUESTS = '/requests',
  INFO = '/info',
  PROFILE = '/profile',
  ARCHIVES = '/archives/archives',
  COMMENTS = '/itineraries/comments',
  SENDINVITES = '/itineraries/invite-people',
  EXPLORE = 'explore',
  BUILDER = 'builder',
  FAVORITES = 'favorites',
  STORIES = 'stories',
  COMMENTS_ROUTE = 'comments',
  NOTIFICATIONS = 'notifications',
  COMMENT_UPDATE_REQUEST = 'comment-update-request',
  TOTAL_MEMBERS = 'total-members',
  INVITE_PEOPLE = 'invite-people',
  FRIEND_REQUESTS = 'friend-requests',
  SEARCH_FRIEND = 'search-friend',
}
