export enum ItenariesRoutesEnum {
  DASHBOARD = '/dashboard',
  ITINERARY = '/itineraries',
  ITINERARY_EXPLORE = '/itineraries/explore',
  ITINERARY_FAVOURITES = '/itineraries/favorites',
  ITINERARY_BUILDER = '/itineraries/builder',
  SEARCH = '/search/',
  REQUESTS = '/requests',
  INFO = '/info',
  PROFILE = '/profile',
  ARCHIVES = '/archives/archives',
  ITINERARY_DETAIL = 'detail',
  ITINERARY_SUMMARY = 'summary',
  ITINERARY_MAP = 'map',
  ITINERARY_OTHER_DETAILS = 'other-details',
  BRANCHED_ITINERARIES = 'branch',
  ADVANCED_FILTER = 'filter',
}
